# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

FROM mcr.microsoft.com/windows/nanoserver:ltsc2019@sha256:1a212d0a200046130ae7a89630b5676121964ec22658bcaf5bb4dd7533cda434

WORKDIR /app

COPY . .

LABEL org.opencontainers.image.source=https://github.com/Alan-Jowett/bpf_conformance
LABEL org.opencontainers.image.description="BPF Conformance container image"
LABEL org.opencontainers.image.licenses=MIT