# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

FROM mcr.microsoft.com/windows/nanoserver:ltsc2019@sha256:ecd58cb94454ed143639e44d28abf240d4f1c0f1566574a58d7f179027fad80d

WORKDIR /app

COPY . .

LABEL org.opencontainers.image.source=https://github.com/Alan-Jowett/bpf_conformance
LABEL org.opencontainers.image.description="BPF Conformance container image"
LABEL org.opencontainers.image.licenses=MIT