# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

FROM mcr.microsoft.com/windows/nanoserver:ltsc2019@sha256:d3bd9a71fc0c0e7f768c607fdbc60cba66ace7a2fc833bcb01992c247d7d78df

WORKDIR /app

COPY . .

LABEL org.opencontainers.image.source=https://github.com/Alan-Jowett/bpf_conformance
LABEL org.opencontainers.image.description="BPF Conformance container image"
LABEL org.opencontainers.image.licenses=MIT