
# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT
#
# For documentation on the format of this file, see
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /Docker/Linux
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /Docker/Windows
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"
